spring:
  datasource:
    url: jdbc:h2:mem:testes
    username: test
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: h2
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

---
environment: test
spring:
  datasource:
    url: jdbc:h2:mem:testes
    username: test
    password: test
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
  h2:
    console:
      enabled: true
