spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    database: h2
    show_sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true

---
environment: test
spring:
  datasource:
    url:
    username:
    password:
    driver-class-name:
  jpa:
    database: h2
  h2:
    console:
      enabled: true
